@begincomposite damagescomposite begin
    regions = Index()

    Component(impactagriculture)
    Component(impactbiodiversity)
    Component(impactcardiovascularrespiratory)
    Component(impactcooling)
    Component(impactdiarrhoea)
    Component(impactextratropicalstorms)
    Component(impactforests)
    Component(impactheating)
    Component(impactvectorbornediseases)
    Component(impacttropicalstorms)
    Component(vslvmorb)
    Component(impactdeathmorbidity)
    Component(impactwaterresources)
    Component(impactsealevelrise)
    Component(impactaggregation)

    # From SocioEconomic Composite Component
    population = Parameter()
    income = Parameter()
    plus = Parameter()
    urbpop = Parameter()
    cumaeei = Parameter()
    area = Parameter()

    # From Climate Composite Component
    temp = Parameter()
    acco2 = Parameter()
    regtmp = Parameter()
    regstmp = Parameter()
    nospecies = Parameter()
    sea = Parameter()

    connect(impactagriculture.population, population)
    connect(impactagriculture.income, income)
    connect(impactbiodiversity.income, income)
    connect(impactbiodiversity.population, population)
    connect(impactcardiovascularrespiratory.population, population)
    connect(impactcardiovascularrespiratory.plus, plus)
    connect(impactcardiovascularrespiratory.urbpop, urbpop)
    connect(impactcooling.population, population)
    connect(impactcooling.income, income)
    connect(impactcooling.cumaeei, cumaeei)
    connect(impactdiarrhoea.population, population)
    connect(impactdiarrhoea.income, income)
    connect(impactextratropicalstorms.population, population)
    connect(impactextratropicalstorms.income, income)
    connect(impactforests.population, population)
    connect(impactforests.income, income)
    connect(impactheating.population, population)
    connect(impactheating.income, income)
    connect(impactheating.cumaeei, cumaeei)
    connect(impactvectorbornediseases.population, population)
    connect(impactvectorbornediseases.income, income)
    connect(impacttropicalstorms.population, population)
    connect(impacttropicalstorms.income, income)
    connect(vslvmorb.population, population)
    connect(vslvmorb.income, income)
    connect(impactwaterresources.population, population)
    connect(impactwaterresources.income, income)
    connect(impactsealevelrise.population, population)
    connect(impactsealevelrise.income, income)
    connect(impactaggregation.income, income)
    connect(impactsealevelrise.area, area)

    connect(impactagriculture.temp, temp)
    connect(impactbiodiversity.temp, temp)
    connect(impactcardiovascularrespiratory.temp, temp)
    connect(impactcooling.temp, temp)
    connect(impactforests.temp, temp)
    connect(impactheating.temp, temp)
    connect(impactvectorbornediseases.temp, temp)
    connect(impactwaterresources.temp, temp)

    connect(impactagriculture.acco2, acco2)
    connect(impactextratropicalstorms.acco2, acco2)
    connect(impactforests.acco2, acco2)

    connect(impactdiarrhoea.regtmp, regtmp)
    connect(impacttropicalstorms.regstmp, regstmp)
    connect(impactbiodiversity.nospecies, nospecies)
    connect(impactsealevelrise.sea, sea)


    connect(impactdeathmorbidity.vsl, vslvmorb.vsl)
    connect(impactdeathmorbidity.vmorb, vslvmorb.vmorb)
    connect(impactdeathmorbidity.population, population.population)
    connect(impactdeathmorbidity.dengue, impactvectorbornediseases.dengue)
    connect(impactdeathmorbidity.schisto, impactvectorbornediseases.schisto)
    connect(impactdeathmorbidity.malaria, impactvectorbornediseases.malaria)
    connect(impactdeathmorbidity.cardheat, impactcardiovascularrespiratory.cardheat)
    connect(impactdeathmorbidity.cardcold, impactcardiovascularrespiratory.cardcold)
    connect(impactdeathmorbidity.resp, impactcardiovascularrespiratory.resp)
    connect(impactdeathmorbidity.diadead, impactdiarrhoea.diadead)
    connect(impactdeathmorbidity.hurrdead, impacttropicalstorms.hurrdead)
    connect(impactdeathmorbidity.extratropicalstormsdead, impactextratropicalstorms.extratropicalstormsdead)
    connect(impactdeathmorbidity.diasick, impactdiarrhoea.diasic)

    # I believe that the component for "impactaggregation" is what should now be the Composite Component. Is this the case?
    connect(impactaggregation.heating, impactheating.heating)
    connect(impactaggregation.cooling, impactcooling.cooling)
    connect(impactaggregation.agcost, impactagriculture.agcost)
    connect(impactaggregation.species, impactbiodiversity.species)
    connect(impactaggregation.water, impactwaterresources.water)
    connect(impactaggregation.hurrdam, impacttropicalstorms.hurrdam)
    connect(impactaggregation.extratropicalstormsdam, impactextratropicalstorms.extratropicalstormsdam)
    connect(impactaggregation.forests, impactforests.forests)
    connect(impactaggregation.drycost, impactsealevelrise.drycost)
    connect(impactaggregation.protcost, impactsealevelrise.protcost)
    connect(impactaggregation.entercost, impactsealevelrise.entercost)
    connect(impactaggregation.deadcost, impactdeathmorbidity.deadcost)
    connect(impactaggregation.morbcost, impactdeathmorbidity.morbcost)
    connect(impactaggregation.wetcost, impactsealevelrise.wetcost)
    connect(impactaggregation.leavecost, impactsealevelrise.leavecost)

    landloss = Variable(impactsealevelrise.landloss)
    enter = Variable(impactsealevelrise.enter)
    leave = Variable(impactsealevelrise.leave)
    dead = Variable(impactdeathmorbidity.dead)
    eloss = Variable(impactaggregation.eloss)
    sloss = Variable(impactaggregation.sloss)

end