@begincomposite damagescomposite begin
    regions = Index()

    Component(impactagriculture)
    Component(impactbiodiversity)
    Component(impactcardiovascularrespiratory)
    Component(impactcooling)
    Component(impactdiarrhoea)
    Component(impactextratropicalstorms)
    Component(impactforests)
    Component(impactheating)
    Component(impactvectorbornediseases)
    Component(impacttropicalstorms)
    Component(vslvmorb)
    Component(impactdeathmorbidity)
    Component(impactwaterresources)
    Component(impactsealevelrise)
    Component(impactaggregation)

    connect(impactdeathmorbidity.vsl, vslvmorb.vsl)
    connect(impactdeathmorbidity.vmorb, vslvmorb.vmorb)
    connect(impactdeathmorbidity.population, population.population)
    connect(impactdeathmorbidity.dengue, impactvectorbornediseases.dengue)
    connect(impactdeathmorbidity.schisto, impactvectorbornediseases.schisto)
    connect(impactdeathmorbidity.malaria, impactvectorbornediseases.malaria)
    connect(impactdeathmorbidity.cardheat, impactcardiovascularrespiratory.cardheat)
    connect(impactdeathmorbidity.cardcold, impactcardiovascularrespiratory.cardcold)
    connect(impactdeathmorbidity.resp, impactcardiovascularrespiratory.resp)
    connect(impactdeathmorbidity.diadead, impactdiarrhoea.diadead)
    connect(impactdeathmorbidity.hurrdead, impacttropicalstorms.hurrdead)
    connect(impactdeathmorbidity.extratropicalstormsdead, impactextratropicalstorms.extratropicalstormsdead)
    connect(impactdeathmorbidity.diasick, impactdiarrhoea.diasic)

    # TODO: Refactor impactaggregation
    connect(impactaggregation.heating, impactheating.heating)
    connect(impactaggregation.cooling, impactcooling.cooling)
    connect(impactaggregation.agcost, impactagriculture.agcost)
    connect(impactaggregation.species, impactbiodiversity.species)
    connect(impactaggregation.water, impactwaterresources.water)
    connect(impactaggregation.hurrdam, impacttropicalstorms.hurrdam)
    connect(impactaggregation.extratropicalstormsdam, impactextratropicalstorms.extratropicalstormsdam)
    connect(impactaggregation.forests, impactforests.forests)
    connect(impactaggregation.drycost, impactsealevelrise.drycost)
    connect(impactaggregation.protcost, impactsealevelrise.protcost)
    connect(impactaggregation.entercost, impactsealevelrise.entercost)
    connect(impactaggregation.deadcost, impactdeathmorbidity.deadcost)
    connect(impactaggregation.morbcost, impactdeathmorbidity.morbcost)
    connect(impactaggregation.wetcost, impactsealevelrise.wetcost)
    connect(impactaggregation.leavecost, impactsealevelrise.leavecost)

    landloss = Variable(impactsealevelrise.landloss)
    enter = Variable(impactsealevelrise.enter)
    leave = Variable(impactsealevelrise.leave)
    dead = Variable(impactdeathmorbidity.dead)
    eloss = Variable(impactaggregation.eloss)
    sloss = Variable(impactaggregation.sloss)

end